import React, { useEffect, useState } from "react";
import { Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { formatDate } from "../../../../helpers";
import { jwtDecode } from "jwt-decode";

const styles = StyleSheet.create({
  footer: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 1,
    position: "absolute",
    bottom: "16px",
    left: "16px",
    right: "16px",
    padding: 1,
  },
  footerText: {
    fontSize: 7,
    textAlign: "right",
    padding: 1,
  },
});

const PdfFooter = () => {
  const [loggedInUser, setLoggedInUser] = useState(null);
  useEffect(() => {
    const token = localStorage.getItem("authToken");
    let decodedToken = jwtDecode(token);
    setLoggedInUser(decodedToken);
  }, []);

  return (
    <View style={styles.footer}>
      <Text style={[styles.footerText]}>
        Report generated by {loggedInUser?.firstName} {loggedInUser?.lastName} (
        {loggedInUser?.userId}) on {formatDate("DD MMM YYYY hh:mm a")}
      </Text>
    </View>
  );
};

export default PdfFooter;
