const NEVER_CHANGING_VALS = {
  PAT_TYPE_OP: "PATTYPE02",
  PAT_TYPE_IP: "PATTYPE01",
  PAT_TYPE_EMER: "PATTYPE03",
  PAT_CAT_GENERAL: "PATCAT001",
  PAT_CAT_PAYER: "PATCAT002",
  PAY_TYPE_INSURANCE: "PAYTYPE003",
  DR_CONSULT_PAY_SER_CODE: 1
};
module.exports = NEVER_CHANGING_VALS
